name: Publish to GHCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Build
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: GHCR Login
      run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Docker Push
      run: docker push ghcr.io/${{ github.repository }}:latest
